[package]
name = "tutorial"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tutorial"
path = "src/tutorial.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.3", features = ["derive"] }
